[phases.setup]
# OJO: Agregué la librería 'mariadb-connector-c' que a veces es necesaria para que pdo_mysql jale bien en Linux
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mysqlnd", "mariadb-connector-c", "composer", "nodejs", "npm"]

[phases.build]
cmds = [
    "npm install",
    "npm run build",
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT" 